[project]
name = "try-uv-dependabot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "botocore>=1.37.11",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
